import { VerticalBox, HorizontalBox, Button, Slider } from "std-widgets.slint";


export component AppWindow inherits Window {
    title: "Hello from slint";

    VerticalBox {
        Text {
            text: "Hello from slint!";
            vertical-alignment: TextVerticalAlignment.center;
            horizontal-alignment: TextHorizontalAlignment.center;

            font-size: 18px * (sin(360deg * animation-tick() / 3s) + 2);
            // font-size: sli.value * 1px;
        }

        // sli := Slider {
        //     minimum: 18.;
        //     maximum: 32.;
        //     max-height: 20px;
        // }
    }
}
